### ISSUE TITLE
Error while installing with composer

### ISSUE THREAD

**Issue by laziz-karimov** [bryglen/yii2-twillio#1]
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package bryglen/yii2-twillio could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by bryglen** [comment]
what is your composer.json?

**Comment by laziz-karimov** [comment]
{
    "name": "yiisoft/yii2-app-basic",
    "description": "Yii 2 Basic Application Template",
    "keywords": ["yii2", "framework", "basic", "application template"],
    "homepage": "http://www.yiiframework.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "_",
        "yiisoft/yii2-bootstrap": "_",
        "yiisoft/yii2-swiftmailer": "_",
        "codemix/yii2-localeurls": "~1.0",
        "yiisoft/yii2-jui": "~2.0",
        "rmrevin/yii2-fontawesome": "~2.9",
        "yiisoft/yii2-authclient": "^2.0",
        "kartik-v/yii2-widget-fileinput": "_"
    },
    "require-dev": {
        "yiisoft/yii2-codeception": "_",
        "yiisoft/yii2-debug": "_",
        "yiisoft/yii2-gii": "_",
        "yiisoft/yii2-faker": "_"
    },
    "config": {
        "process-timeout": 1800
    },
    "scripts": {
        "post-create-project-cmd": [
            "yii\composer\Installer::postCreateProject"
        ]
    },
    "extra": {
        "yii\composer\Installer::postCreateProject": {
            "setPermission": [
                {
                    "runtime": "0777",
                    "web/assets": "0777",
                    "yii": "0755"
                }
            ],
            "generateCookieValidationKey": [
                "config/web.php"
            ]
        },
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    }
}

**Comment by bryglen** [comment]
you didn't include my library into your composer.json

**Comment by laziz-karimov** [comment]
I did, composer reverted it, after Installation was failed. As you can see in my very first comment (Installation failed, reverting ./composer.json to its original content.)
It was
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "_",
        "yiisoft/yii2-bootstrap": "_",
        "yiisoft/yii2-swiftmailer": "_",
        "codemix/yii2-localeurls": "~1.0",
        "yiisoft/yii2-jui": "~2.0",
        "rmrevin/yii2-fontawesome": "~2.9",
        "yiisoft/yii2-authclient": "^2.0",
        "kartik-v/yii2-widget-fileinput": "_",
        "bryglen/yii2-twillio": "*"
    },

**Comment by laziz-karimov** [comment]
The package has stability as "dev", 
so "minimum-stability": "stable" must be changed to
"minimum-stability": "dev"

Moreover 
'components' => [
    'twillio' => [
        'class' => 'bryglen\braintree\Braintree',
        'sid' => 'your_sid',
        'token' => 'your_token',
    ]
]
to
'components' => [
    'twillio' => [
        'class' => 'ryglen\twillio\Twillio',
        'sid' => 'your_sid',
        'token' => 'your_token',
    ]
]

At least it worked for me
